[tool.poetry]
name = "course-work-04"
version = "0.1.0"
description = ""
authors = ["Gleb Skotnikov <skotnikov.nsk@gmail.com>"]
readme = "README.md"
packages = [{include = "course_work_04"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
